.TH PPJSON 1 "2015-12-31" "PPJSON v1.2.0" "JSON Pretty Printer"
.\"
.\"       It's hand-written, baby
.\"
.nh   .\" Disable hyphenation
.ad l .\" Disable justification: left-align only
.SH NAME
\fBppjson\fP \-\- Pretty\-print JSON data for terminal output
.SH SYNOPSIS
\fBppjson\fP [\fIoptions\fP] \fIfilename\fP
.SH DESCRIPTION
Pretty\-print and colourise JSON data for terminal display.
.PP
JSON data can be supplied by \fIfilename\fP, or piped through standard input:
.PP
.nf
.RS
\fBppjson\fP json.file
\fBppjson\fP < json.file
\fBnode\fP generate-and-echo-json.js | ppjson
.RE
.fi
.SH OPTIONS
Each boolean option mentioned below is enabled by default.
.IP "\fB\-m\fP \fIBOOL\fP, \fB\-\-mutilate\fP=\fIBOOL\fP"
Unquote property identifiers in object literals:
.PP
.nf
.RS
       { "okay" : true }  # Before
    \fB\->\fP {  okay  : true }  # After
    
Unsafe property identifiers are left untouched:
    
       { "o.k?" : false }  # Before AND after
.RE
.fi
.IP "\fB\-u\fP \fIBOOL\fP, \fB\-\-underline\-urls\fP=\fIBOOL\fP"
Decorate URL patterns with underlines.
.IP "\fB\-c\fP \fIBOOL\fP, \fB\-\-colour\fP=\fIBOOL\fP, \fB\-\-colours\fP=\fIBOOL\fP, \fB\-\-colourise\fP=\fIBOOL\fP"
Colourise the beautified output. Turning this off disables colours.
.IP "\fB\-i\fP \fIWIDTH\fP, \fB\-\-indent\fP=\fIWIDTH\fP"
Set the width of each indentation level, expressed in spaces.
.IP "\fB\-a\fP, \fB\-\-alphabetise\fP"
Order the properties of objects by alphabetic order, not the order in which they were enumerated (the default).
This option is \fIoff\fP by default.
.IP "\fB\-p\fP, \fB\-\-paged\fP"
Display output using \fB`less -Ri`\fP if it's too long to fit in one window. This option is \fIoff\fP by default.
.IP "\fB\-?\fP, \fB\-h\fP, \fB\-\-help\fP"
Display a brief help summary and exit.
.SH PASSING OPTIONS
The \fIBOOL\fP options described above are all enabled by default.
You can disable them by passing \fB0\fP, \fBfalse\fP, \fBno\fP or \fBoff\fP as values (their capitalisation doesn't matter):
.nf
.RS
    
# All these lines are equivalent
\fBppjson\fP \-\-mutilate=no
\fBppjson\fP \-\-mutilate OFF
\fBppjson\fP \-\-mutilate 0
\fBppjson\fP  \-m0
\fBppjson\fP \-\-mutilate false
    
.RE
.fi
Option order is inconsequential; they may be listed before or after a filename:
.nf
.RS
    
# Same damn thing
\fBppjson\fP \-m0 file.json
\fBppjson\fP file.json \-m0
    
.RE
.fi
.SH EXAMPLES
.TP
Use 2 spaces instead of 4:
\fBppjson\fP \-\-indent=2 file.json
.TP
Disable colours:
\fBppjson\fP \-c0 < file.json
.TP
Don't remove quote marks from property names:
\fBppjson\fP \-m false file.json
.br
\fBppjson\fP \-\-mutilate no < file.json
.SH ENVIRONMENT
Colours can be controlled using environment variables.
Each value maps to an ANSI colour index.
.PP
.nf
.RS
.I "VARIABLE                 DEFAULT"

.BR "PPJSON_COLOUR_STRINGS       "2
.BR "PPJSON_COLOUR_NUMBERS       "2
.BR "PPJSON_COLOUR_TRUE          "6
.BR "PPJSON_COLOUR_FALSE         "6
.BR "PPJSON_COLOUR_NULL          "6
.BR "PPJSON_COLOUR_PUNCT         "8
.BR "PPJSON_COLOUR_ERROR         "1
.RE
.fi
.PP
.SH EXIT STATUS
If a specified filename couldn't be accessed or located, the program exits with an error code of \fB2\fP.
.SH AUTHOR
Copyright (c) 2016 John Gardner <\fIgardnerjohng@gmail.com\fP>.
.PP
Freely released under the ISC license. See also \fIhttp://opensource.org/licenses/ISC\fP.
